services:
  - type: web
    name: aiskcon-construction
    env: static
    buildCommand: echo "No build required"
    staticPublishPath: ./
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html