services:
  - type: static
    name: aiskcon-construction
    env: static
    buildCommand: ""
    staticPublishPath: /
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache