services:
  - type: static
    name: aiskcon-construction
    env: static
    buildCommand: npm install
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache